#if !canImport(ObjectiveC)
import XCTest

extension AnyPredicateEquatableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyPredicateEquatableTests = [
        ("test_satify_shoudReturnFalseWithInt", test_satify_shoudReturnFalseWithInt),
        ("test_satify_shoudReturnTrueWithInt", test_satify_shoudReturnTrueWithInt),
        ("test_satify_shouldReturnFalseWithArray", test_satify_shouldReturnFalseWithArray),
        ("test_satify_shouldReturnFalseWithBool", test_satify_shouldReturnFalseWithBool),
        ("test_satify_shouldReturnFalseWithString", test_satify_shouldReturnFalseWithString),
        ("test_satify_shouldReturnTrueWithArray", test_satify_shouldReturnTrueWithArray),
        ("test_satify_shouldReturnTrueWithBool", test_satify_shouldReturnTrueWithBool),
        ("test_satify_shouldReturnTrueWithString", test_satify_shouldReturnTrueWithString),
        ("test_satisfy_shouldReturnFalseIfNotEquals", test_satisfy_shouldReturnFalseIfNotEquals),
        ("test_satisfy_shouldReturnTrueIfEquals", test_satisfy_shouldReturnTrueIfEquals),
    ]
}

extension DefaultFunctionBehaviourTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DefaultFunctionBehaviourTests = [
        ("test_handle_shouldReturnDefaultCustom", test_handle_shouldReturnDefaultCustom),
        ("test_handle_shouldReturnNullOnUnknownType", test_handle_shouldReturnNullOnUnknownType),
        ("test_handleThrowable_shouldReturnDefaultCustom", test_handleThrowable_shouldReturnDefaultCustom),
        ("test_handleThrowable_shouldReturnNullOnUnknownType", test_handleThrowable_shouldReturnNullOnUnknownType),
    ]
}

extension FunctionBehaviourRegisterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionBehaviourRegisterTests = [
        ("test_recordedBehaviours_shouldReturnDefaultFunctionBehaviourWhenNoMatchs", test_recordedBehaviours_shouldReturnDefaultFunctionBehaviourWhenNoMatchs),
        ("test_recordedBehaviours_shouldReturnFunctionBehaviourMatched", test_recordedBehaviours_shouldReturnFunctionBehaviourMatched),
    ]
}

extension FunctionBehaviourTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionBehaviourTests = [
        ("test_handle_shouldCallHandlerWithCorrectParameters", test_handle_shouldCallHandlerWithCorrectParameters),
        ("test_handle_shouldReturnNilIfHandlerThrows", test_handle_shouldReturnNilIfHandlerThrows),
        ("test_handle_shouldReturnNilIfNotSameType", test_handle_shouldReturnNilIfNotSameType),
        ("test_handle_shouldReturnValueFormHandler", test_handle_shouldReturnValueFormHandler),
        ("test_handleThrowable_shouldCallHandlerWithCorrectParameters", test_handleThrowable_shouldCallHandlerWithCorrectParameters),
        ("test_handleThrowable_shouldReturnNilIfNotSameType", test_handleThrowable_shouldReturnNilIfNotSameType),
        ("test_handleThrowable_shouldReturnValueFormHandler", test_handleThrowable_shouldReturnValueFormHandler),
        ("test_handleThrowable_shouldThrowsIfHandlerThrows", test_handleThrowable_shouldThrowsIfHandlerThrows),
    ]
}

extension FunctionCallRegisterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionCallRegisterTests = [
        ("test_recordedCalls_shouldReturnEmptyWhenNoFunctionCall", test_recordedCalls_shouldReturnEmptyWhenNoFunctionCall),
        ("test_recordedCalls_shouldReturnEmptyWhenNoFunctionCallMatched", test_recordedCalls_shouldReturnEmptyWhenNoFunctionCallMatched),
        ("test_recordedCalls_shouldReturnFunctionCallsMatched", test_recordedCalls_shouldReturnFunctionCallsMatched),
    ]
}

extension FunctionIdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionIdentifierTests = [
        ("test_callDescription_withNoParameters", test_callDescription_withNoParameters),
        ("test_callDescription_withParameters", test_callDescription_withParameters),
    ]
}

extension InternalErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InternalErrorTests = [
        ("test_description_withCast", test_description_withCast),
        ("test_description_withCastTwice", test_description_withCastTwice),
        ("test_description_withNoDefinedBehaviour", test_description_withNoDefinedBehaviour),
        ("test_description_withTooManyDefinedBehaviour", test_description_withTooManyDefinedBehaviour),
    ]
}

extension MockDefaultExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockDefaultExtensionTests = [
        ("test_default_Bool", test_default_Bool),
        ("test_default_Int", test_default_Int),
        ("test_default_String", test_default_String),
    ]
}

extension MockDefaultIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockDefaultIntegrationTests = [
        ("test_function_shouldReturnDefaultCustom", test_function_shouldReturnDefaultCustom),
        ("test_functionBool_shouldReturnDefaultBool", test_functionBool_shouldReturnDefaultBool),
        ("test_functionInt_shouldReturnDefaultInt", test_functionInt_shouldReturnDefaultInt),
        ("test_functionString_shouldReturnDefaultString", test_functionString_shouldReturnDefaultString),
        ("test_functionVoid_shouldReturnVoid", test_functionVoid_shouldReturnVoid),
    ]
}

extension MockGivenIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockGivenIntegrationTests = [
        ("test_function_shouldReturnDefaultValueIfNoMatch", test_function_shouldReturnDefaultValueIfNoMatch),
        ("test_function_shouldReturnValueFromWillCompletion", test_function_shouldReturnValueFromWillCompletion),
        ("test_function_shouldReturnValueFromWillReturnValue", test_function_shouldReturnValueFromWillReturnValue),
        ("test_function_shouldReturnValueFromWillReturnValues", test_function_shouldReturnValueFromWillReturnValues),
        ("test_function_shouldThrowErrorFromWillCompletion", test_function_shouldThrowErrorFromWillCompletion),
        ("test_function_shouldThrowFromWillThrowError", test_function_shouldThrowFromWillThrowError),
        ("test_function_shouldThrowFromWillThrowErrors", test_function_shouldThrowFromWillThrowErrors),
        ("test_given_shouldCallCompletionWithMockGiven", test_given_shouldCallCompletionWithMockGiven),
    ]
}

extension MockGivenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockGivenTests = [
        ("test_given_shouldFailWithCast", test_given_shouldFailWithCast),
        ("test_given_shouldPass", test_given_shouldPass),
        ("test_givenCompletion_shouldPass", test_givenCompletion_shouldPass),
    ]
}

extension MockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockTests = [
        ("test_mocked_shouldFailWithNoDefinedBehaviour", test_mocked_shouldFailWithNoDefinedBehaviour),
        ("test_mocked_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO", test_mocked_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO),
        ("test_mocked_shouldFailWithTooManyDefinedBehaviour", test_mocked_shouldFailWithTooManyDefinedBehaviour),
        ("test_mocked_shouldRecordCallIntoCallRegister", test_mocked_shouldRecordCallIntoCallRegister),
        ("test_mocked_shouldReturnValueFromBehaviour", test_mocked_shouldReturnValueFromBehaviour),
        ("test_mockedVoid_shouldCallBehaviour", test_mockedVoid_shouldCallBehaviour),
        ("test_mockedVoid_shouldFailWithNoDefinedBehaviour", test_mockedVoid_shouldFailWithNoDefinedBehaviour),
        ("test_mockedVoid_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO", test_mockedVoid_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO),
        ("test_mockedVoid_shouldFailWithTooManyDefinedBehaviour", test_mockedVoid_shouldFailWithTooManyDefinedBehaviour),
        ("test_mockedVoid_shouldRecordCallIntoCallRegister", test_mockedVoid_shouldRecordCallIntoCallRegister),
        ("test_wrappedValue_shouldFailWithCast", test_wrappedValue_shouldFailWithCast),
    ]
}

extension MockThenIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockThenIntegrationTests = [
        ("test_function_shouldBeCalledWhenParametersMatched", test_function_shouldBeCalledWhenParametersMatched),
        ("test_receivedParameters_whenParametersMatched", test_receivedParameters_whenParametersMatched),
        ("test_then_shouldCallCompletionWithMockThen", test_then_shouldCallCompletionWithMockThen),
    ]
}

extension MockThenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockThenTests = [
        ("test_then_shouldFailWithCast", test_then_shouldFailWithCast),
        ("test_then_shouldPass", test_then_shouldPass),
        ("test_thenCompletion_shouldPass", test_thenCompletion_shouldPass),
    ]
}

extension MockThrowableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockThrowableTests = [
        ("test_mockedThrowable_shouldFailWithNoDefinedBehaviour", test_mockedThrowable_shouldFailWithNoDefinedBehaviour),
        ("test_mockedThrowable_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO", test_mockedThrowable_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO),
        ("test_mockedThrowable_shouldFailWithTooManyDefinedBehaviour", test_mockedThrowable_shouldFailWithTooManyDefinedBehaviour),
        ("test_mockedThrowable_shouldRecordCallIntoCallRegister", test_mockedThrowable_shouldRecordCallIntoCallRegister),
        ("test_mockedThrowable_shouldReturnValueFromBehaviour", test_mockedThrowable_shouldReturnValueFromBehaviour),
        ("test_mockedThrowable_shouldThrowErrorFromBehaviour", test_mockedThrowable_shouldThrowErrorFromBehaviour),
        ("test_mockedThrowableVoid_shouldCallBehaviour", test_mockedThrowableVoid_shouldCallBehaviour),
        ("test_mockedThrowableVoid_shouldFailWithNoDefinedBehaviour", test_mockedThrowableVoid_shouldFailWithNoDefinedBehaviour),
        ("test_mockedThrowableVoid_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO", test_mockedThrowableVoid_shouldFailWithNoDefinedBehaviourWhenReturnTypeKO),
        ("test_mockedThrowableVoid_shouldFailWithTooManyDefinedBehaviour", test_mockedThrowableVoid_shouldFailWithTooManyDefinedBehaviour),
        ("test_mockedThrowableVoid_shouldRecordCallIntoCallRegister", test_mockedThrowableVoid_shouldRecordCallIntoCallRegister),
        ("test_mockedThrowableVoid_shouldThrowErrorFromBehaviour", test_mockedThrowableVoid_shouldThrowErrorFromBehaviour),
    ]
}

extension MockableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockableTests = [
        ("test_disambiguate_shouldReturnSameMockableWithDisambiguatedReturnType", test_disambiguate_shouldReturnSameMockableWithDisambiguatedReturnType),
        ("test_will_shouldCorrectlyRegisterBahaviour", test_will_shouldCorrectlyRegisterBahaviour),
        ("test_willReturn_shouldCorrectlyRegisterBahaviour", test_willReturn_shouldCorrectlyRegisterBahaviour),
        ("test_willReturn_withListShouldCorrectlyRegisterBahaviour", test_willReturn_withListShouldCorrectlyRegisterBahaviour),
        ("test_willThrow_shouldCorrectlyRegisterBahaviour", test_willThrow_shouldCorrectlyRegisterBahaviour),
    ]
}

extension PredicatBoolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PredicatBoolTests = [
        ("test_isFalse_description", test_isFalse_description),
        ("test_isFalse_shouldReturnFalse", test_isFalse_shouldReturnFalse),
        ("test_isFalse_shouldReturnTrue", test_isFalse_shouldReturnTrue),
        ("test_isTrue_description", test_isTrue_description),
        ("test_isTrue_shouldReturnFalse", test_isTrue_shouldReturnFalse),
        ("test_isTrue_shouldReturnTrue", test_isTrue_shouldReturnTrue),
    ]
}

extension PredicateComparableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PredicateComparableTests = [
        ("test_equalsTo_description", test_equalsTo_description),
        ("test_equalsTo_shouldReturnFalseIfComparisonReturnFalse", test_equalsTo_shouldReturnFalseIfComparisonReturnFalse),
        ("test_equalsTo_shouldReturnTrueIfComparisonReturnTrue", test_equalsTo_shouldReturnTrueIfComparisonReturnTrue),
        ("test_lessThan_description", test_lessThan_description),
        ("test_lessThan_shouldReturnFalseIfComparisonReturnFalse", test_lessThan_shouldReturnFalseIfComparisonReturnFalse),
        ("test_lessThan_shouldReturnTrueIfComparisonReturnTrue", test_lessThan_shouldReturnTrueIfComparisonReturnTrue),
        ("test_lessThanOrEqualsTo_description", test_lessThanOrEqualsTo_description),
        ("test_lessThanOrEqualsTo_shouldReturnFalseIfComparisonReturnFalse", test_lessThanOrEqualsTo_shouldReturnFalseIfComparisonReturnFalse),
        ("test_lessThanOrEqualsTo_shouldReturnTrueIfComparisonReturnTrue", test_lessThanOrEqualsTo_shouldReturnTrueIfComparisonReturnTrue),
        ("test_moreThan_description", test_moreThan_description),
        ("test_moreThan_shouldReturnFalseIfComparisonReturnFalse", test_moreThan_shouldReturnFalseIfComparisonReturnFalse),
        ("test_moreThan_shouldReturnTrueIfComparisonReturnTrue", test_moreThan_shouldReturnTrueIfComparisonReturnTrue),
        ("test_moreThanOrEqualsTo_description", test_moreThanOrEqualsTo_description),
        ("test_moreThanOrEqualsTo_shouldReturnFalseIfComparisonReturnFalse", test_moreThanOrEqualsTo_shouldReturnFalseIfComparisonReturnFalse),
        ("test_moreThanOrEqualsTo_shouldReturnTrueIfComparisonReturnTrue", test_moreThanOrEqualsTo_shouldReturnTrueIfComparisonReturnTrue),
    ]
}

extension PredicateOptionalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PredicateOptionalTests = [
        ("test_isNil_description", test_isNil_description),
        ("test_isNil_shouldReturnFalse", test_isNil_shouldReturnFalse),
        ("test_isNil_shouldReturnTrue", test_isNil_shouldReturnTrue),
    ]
}

extension PredicateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PredicateTests = [
        ("test_any_description", test_any_description),
        ("test_any_shouldReturnFalse", test_any_shouldReturnFalse),
        ("test_any_shouldReturnTrue", test_any_shouldReturnTrue),
        ("test_match_description", test_match_description),
        ("test_match_KeyPathDescription", test_match_KeyPathDescription),
        ("test_match_shouldReturnFalseIfInputNotMatched", test_match_shouldReturnFalseIfInputNotMatched),
        ("test_match_shouldReturnFalseIfInputNotMatchedByAnyPredicate", test_match_shouldReturnFalseIfInputNotMatchedByAnyPredicate),
        ("test_match_shouldReturnFalseIfInputNotSameReference", test_match_shouldReturnFalseIfInputNotSameReference),
        ("test_match_shouldReturnFalseIfKeyPathReturnFalse", test_match_shouldReturnFalseIfKeyPathReturnFalse),
        ("test_match_shouldReturnTrueIfInputMatched", test_match_shouldReturnTrueIfInputMatched),
        ("test_match_shouldReturnTrueIfInputMatchedByAnyPredicate", test_match_shouldReturnTrueIfInputMatchedByAnyPredicate),
        ("test_match_shouldReturnTrueIfInputSameReference", test_match_shouldReturnTrueIfInputSameReference),
        ("test_match_shouldReturnTrueIfKeyPathReturnTrue", test_match_shouldReturnTrueIfKeyPathReturnTrue),
        ("test_match_withMatchShouldReturnFalseIfInputIsNotTheSameType", test_match_withMatchShouldReturnFalseIfInputIsNotTheSameType),
        ("test_not_description", test_not_description),
        ("test_not_shouldReturnFalse", test_not_shouldReturnFalse),
        ("test_not_shouldReturnTrue", test_not_shouldReturnTrue),
    ]
}

extension VerifiableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VerifiableTests = [
        ("test_called_shouldNotRecordFailureWhenFunctionCallFromCallRegisterMatched", test_called_shouldNotRecordFailureWhenFunctionCallFromCallRegisterMatched),
        ("test_called_shouldNotRecordFailureWhenFunctionCallFromCallRegisterMatchedTimes", test_called_shouldNotRecordFailureWhenFunctionCallFromCallRegisterMatchedTimes),
        ("test_called_shouldNotRecordFailureWhenFunctionCallFromCallRegisterMatchedTimesExactly", test_called_shouldNotRecordFailureWhenFunctionCallFromCallRegisterMatchedTimesExactly),
        ("test_called_shouldRecordFailureWhenNoFunctionCallFromCallRegisterMatched", test_called_shouldRecordFailureWhenNoFunctionCallFromCallRegisterMatched),
        ("test_called_shouldRecordFailureWhenNoFunctionCallFromCallRegisterMatchedTimes", test_called_shouldRecordFailureWhenNoFunctionCallFromCallRegisterMatchedTimes),
        ("test_called_shouldRecordFailureWhenNoFunctionCallFromCallRegisterMatchedTimesExactly", test_called_shouldRecordFailureWhenNoFunctionCallFromCallRegisterMatchedTimesExactly),
        ("test_disambiguate_shouldReturnSameVerifiableWithDisambiguatedReturnType", test_disambiguate_shouldReturnSameVerifiableWithDisambiguatedReturnType),
        ("test_receivedParameters_shouldAllCallsParametersWhenFunctionCallFromCallRegisterMatched", test_receivedParameters_shouldAllCallsParametersWhenFunctionCallFromCallRegisterMatched),
        ("test_receivedParameters_shouldReturnEmptyWhenNoFunctionCallFromCallRegisterMatched", test_receivedParameters_shouldReturnEmptyWhenNoFunctionCallFromCallRegisterMatched),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnyPredicateEquatableTests.__allTests__AnyPredicateEquatableTests),
        testCase(DefaultFunctionBehaviourTests.__allTests__DefaultFunctionBehaviourTests),
        testCase(FunctionBehaviourRegisterTests.__allTests__FunctionBehaviourRegisterTests),
        testCase(FunctionBehaviourTests.__allTests__FunctionBehaviourTests),
        testCase(FunctionCallRegisterTests.__allTests__FunctionCallRegisterTests),
        testCase(FunctionIdentifierTests.__allTests__FunctionIdentifierTests),
        testCase(InternalErrorTests.__allTests__InternalErrorTests),
        testCase(MockDefaultExtensionTests.__allTests__MockDefaultExtensionTests),
        testCase(MockDefaultIntegrationTests.__allTests__MockDefaultIntegrationTests),
        testCase(MockGivenIntegrationTests.__allTests__MockGivenIntegrationTests),
        testCase(MockGivenTests.__allTests__MockGivenTests),
        testCase(MockTests.__allTests__MockTests),
        testCase(MockThenIntegrationTests.__allTests__MockThenIntegrationTests),
        testCase(MockThenTests.__allTests__MockThenTests),
        testCase(MockThrowableTests.__allTests__MockThrowableTests),
        testCase(MockableTests.__allTests__MockableTests),
        testCase(PredicatBoolTests.__allTests__PredicatBoolTests),
        testCase(PredicateComparableTests.__allTests__PredicateComparableTests),
        testCase(PredicateOptionalTests.__allTests__PredicateOptionalTests),
        testCase(PredicateTests.__allTests__PredicateTests),
        testCase(VerifiableTests.__allTests__VerifiableTests),
    ]
}
#endif
