author: Jordhan Leoture
github_url: https://github.com/leoture/MockSwift
root_url: https://leoture.github.io/MockSwift/
module: MockSwift
output: docs
readme: README.md
xcodebuild_arguments: [-workspace, 'MockSwift.xcworkspace', -scheme, 'MockSwift-Package']
