
if: (branch = master OR branch = develop OR type = pull_request)

env:
  global:
  - SWIFT_VERSION=swift-5.1-DEVELOPMENT-SNAPSHOT-2019-08-16-a

jobs:
  include:

  - stage: Tests
    name: Linux
    os: linux
    language: generic
    dist: trusty
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    script:
      - swift package update
      - swift test

  - stage: Tests
    name: macOS
    os: osx
    osx_image: xcode11
    language: swift
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    before_script:
      - ./scripts/check-linux-tests.sh
    script:
      - swift package update
      - swift test
