
if: (branch = master OR branch = develop OR type = pull_request)

env:
  global:
  - SWIFT_VERSION=swift-5.1

jobs:
  include:

  - stage: Tests
    name: Linux
    os: linux
    language: generic
    dist: trusty
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    script:
      - swift package update
      - swift test

  - stage: Tests
    name: macOS
    os: osx
    osx_image: xcode11
    language: swift
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    before_script:
      - ./scripts/check-linux-tests.sh
    script:
      - swift package update
      - swift test

  - stage: Tests
    name: Xcode
    os: osx
    osx_image: xcode11
    language: swift
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - brew install sourcery
    script:
      - xcodebuild -scheme MockSwift-Package -workspace MockSwift.xcworkspace test
      - xcodebuild -scheme MockSwiftExample -workspace MockSwift.xcworkspace -destination "name=iPhone Xs" test
    after_success:
      - bash <(curl -s https://codecov.io/bash)
