# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

#update_fastlane

default_platform(:mac)

platform :mac do

  desc "Run Swift Package Manager tests"
  lane :spm_tests do
    spm(
      command: "test",
      xcpretty_output: "simple"
    )
  end

  desc "Run Swift Package Manager tests on linux"
  lane :spm_linux_tests do
    sh("docker-compose","up")
  end

  desc "Run MockSwift-Package tests"
  lane :mockswift_package_tests do
    run_tests(
      scheme: "MockSwift-Package",
      clean: true,
      skip_detect_devices: true,
      code_coverage: true,
      result_bundle: true
    )
    slather(
      cobertura_xml: true,
      output_directory: ".",
      scheme: "MockSwift-Package",
      proj: "MockSwift.xcodeproj",
      workspace: "MockSwift.xcworkspace"
    )
  end

  desc "Run MockSwiftExample tests"
  lane :mockswift_example_tests do
    run_tests(
      scheme: "MockSwiftExample",
      clean: true,
    )
  end

  desc "Run mac tests"
  lane :mac_tests do
    spm_tests
    # waiting merge of https://github.com/krzysztofzablocki/Sourcery/commit/aec35890f7ffea016eb78ae0f4eaa28065204fa4
    #mockswift_example_tests 
    mockswift_package_tests
  end

  desc "Run mac & linux tests"
  lane :all_tests do
    sh("swift test --generate-linuxmain")
    mac_tests
    spm_linux_tests
  end
end
