# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

#update_fastlane

default_platform(:mac)

platform :mac do

  desc "Run Swift Package Manager tests"
  lane :spm_tests do
    spm(
      command: "test",
      xcpretty_output: "simple",
      enable_code_coverage: true
    )
  end

  desc "Run Swift Package Manager tests on linux"
  lane :spm_linux_tests do
    sh("docker-compose","up")
  end

  desc "Run mac & linux tests"
  lane :all_tests do
    spm_tests
    spm_linux_tests
  end
end
