name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  
  check-linuxmain:
    runs-on: macOS-latest
    name: Check Linuxmain
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: ./scripts/check-linux-tests.sh 
      
  spm-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    name: Swift Package Manager Tests
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: swift test
  
  mockswift-package:
    runs-on: macOS-latest
    name: MockSwift-Package
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - name: install swiftlint
      run: brew install swiftlint
    - name: xcode test
      run: xcodebuild -workspace MockSwift.xcworkspace -scheme MockSwift-Package -destination 'platform=iOS Simulator,name=iPhone 11' test | xcpretty && exit ${PIPESTATUS[0]}
      
  mockswiftexample:
    runs-on: macOS-latest
    name: MockSwiftExample
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - name: install swiftlint
      run: brew install swiftlint
    - name: install sourcery
      run: brew install sourcery
    - name: xcode test
    - run: xcodebuild -workspace MockSwift.xcworkspace -scheme MockSwiftExample -destination 'platform=iOS Simulator,name=iPhone 11' test | xcpretty && exit ${PIPESTATUS[0]}
