name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:

  linux-tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - name: Build and test
      run: swift test

  macos-tests:
    name: macOS Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        brew install swiftlint sourcery
        bundle install
        swift --version
    - name: Run fastlane
      run: fastlane mac_tests
    - name: Code coverage
      run: bash <(curl -s 'https://codecov.io/bash') -J '^MockSwift$' -t ${{secrets.CODECOV_TOKEN}}
    - name: Code climate
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter upload-coverage
    - name: Danger
      run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
