name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: make
    - run: bash <(curl -s https://codecov.io/bash)
