name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:

  spm-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    name: Swift Package Manager Tests
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: swift test
