name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:

  linux-tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - name: Build and test
      run: swift test

  macos-tests:
    name: macOS Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Prepare
      run: |
        brew install swiftlint sourcery swiftformat
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        swift --version
    - name: Danger
      run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare Code climate
      run: |
        export GIT_BRANCH=${GITHUB_HEAD_REF//refs\/heads\//}
        export GIT_COMMIT_SHA=$(git rev-parse HEAD)
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Run fastlane
      run: bundle exec fastlane mac_tests
    - name: Code coverage
      run: bash <(curl -s 'https://codecov.io/bash') -J '^MockSwift$' -t ${{secrets.CODECOV_TOKEN}}
    - name: Code climate
      run: |
        export GIT_BRANCH=${GITHUB_HEAD_REF//refs\/heads\//}
        export GIT_COMMIT_SHA=$(git rev-parse HEAD)
        xcrun xccov view --report --json fastlane/test_output/MockSwift-Package.test_result.xcresult > coverage.json
        ./cc-test-reporter after-build -d -t xccov --exit-code $? -r ${{ secrets.CC_TEST_REPORTER_ID }}
