name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  
  check-linuxmain:
    runs-on: macOS-latest
    name: Check Linuxmain
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: ./scripts/check-linux-tests.sh 
      
  spm-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    name: Swift Package Manager Tests
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: make spm-tests
  
  mockswift-package:
    runs-on: macOS-latest
    name: MockSwift-Package
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: make MockSwift-Package
      
  mockswiftexample:
    runs-on: macOS-latest
    name: MockSwiftExample
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1'
    - run: make MockSwiftExample
