name: Master

on:
  push:
    branches:
      - master

jobs:

  linux-tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.2'
    - name: Build and test
      run: swift test

  macos-tests:
    name: macOS Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Prepare
      run: |
        brew install swiftlint sourcery
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        swift --version
    - name: Prepare Code climate
      run: |
        export GIT_BRANCH=master
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Run fastlane
      run: bundle exec fastlane mac_tests
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    - name: Codacy
      run: |
        curl -LS -o codacy-coverage-reporter-assembly.jar "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')"
        java -jar codacy-coverage-reporter-assembly.jar report -l Swift -r cobertura.xml
      env:
        CODACY_PROJECT_TOKEN: $${{ secrets.CODACY_TOKEN }}
    - name: Code coverage
      run: bash <(curl -s 'https://codecov.io/bash') -J '^MockSwift$' -t ${{secrets.CODECOV_TOKEN}}
    - name: Code climate
      run: |
        export GIT_BRANCH=master
        xcrun xccov view --report --json fastlane/test_output/MockSwift-Package.xcresult > coverage.json
        ./cc-test-reporter after-build -d -t xccov --exit-code $? -r ${{ secrets.CC_TEST_REPORTER_ID }}
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
