name: Master

on:
  push:
    branches:
      - master

jobs:

  linux-tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.2'
    - name: Build and test
      run: swift test

  macos-tests:
    name: macOS Tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Prepare
      run: |
        brew install swiftlint sourcery
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        swift --version
    - name: Run fastlane
      run: bundle exec fastlane mac_tests
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    - name: Codacy
      run: sh <(curl -Ls https://coverage.codacy.com/get.sh) report -l Swift --force-language -r cobertura.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
