name: Master

on:
  push:
    branches:
      - master

jobs:

  linux-tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@main
      with:
        swift-version: '5.5'
    - name: Build and test
      run: swift test

  macos-tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run fastlane
      run: swift test --enable-code-coverage
