name: Master

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.5"]
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v2
    - name: Get swift version
      run: swift --version
    - name: Build and test
      run: swift test
